Разбивает главную на компоненты с передачей данных между ними
htmlacademy-vue/175289-pizza-1 pull request #2
Opened 2022-05-03 12:04 UTC by yuliyasitnikova

2022-05-03 14:08 UTC, Djaler requested changes

2022-05-03 14:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                  :class="`filling filling--${ingredient.value}`"
лучше сделать, чтоб у AppDrag контролировалось свойство draggable снаружи. Тогда не понадобится тут делать v-if/v-else, а можно будет просто отключать drag-and-drop

2022-05-03 14:08 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.currentValue = this.value;
от этого внутреннего состояния можно избавиться, оно тут лишнее. просто внутри компонента работать напрямую с пропсом value. не мутируя его напрямую, конечно, вместо этого кидаем новое значение в событии

2022-05-03 14:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +    pizza: {
хорошо бы сюда передавать не весь объект пиццы, а только выбранное тесто

2022-05-03 14:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :value="getIngredientCount(ingredient)"
просто как вариант к размышлению - чтоб не нужно было для каждого ингредиента гонять поиск в массиве, можно использовать другую структуру для хранения данных. например, объект, у которого ключ - идентификатор ингредиента, а значение - количество. Тогда мы сможем сделать просто `:value="ingredientCounts[intedient.id] || 0"`

2022-05-03 14:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +          { 'pizza__filling--third': ingredient.count === 3 },
отображение ингредиентов нужно доработать. В ситуации, когда выбрано 2 единицы ингредиента, нужно отобразить, соответственно, 2 div:
pizza__filling pizza__filling--${name}
pizza__filling pizza__filling--${name} pizza__filling--second

Когда выбрано 3, аналогично:
pizza__filling pizza__filling--${name}
pizza__filling pizza__filling--${name} pizza__filling--second
pizza__filling pizza__filling--${name} pizza__filling--third

Тогда отображение будет соответствовать состоянию - чем больше выбрали, тем больше видим

2022-05-09 16:47 UTC, yuliyasitnikova commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.currentValue = this.value;
Убрала, но не получается теперь сделать так, чтобы input отображал значение value, а не то, что ввел пользователь. С локальной переменной я обновляла значение напрямую в setValue. https://monosnap.com/file/v4SLMAyPKOnJ5q6nhEfakwE1orDOG4

2022-05-09 17:21 UTC, yuliyasitnikova commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :value="getIngredientCount(ingredient)"
метод getIngredientCount оставила, так как получаю количество для ItemCounter и определения, можно ли перетаскивать ингредиент на пиццу (чтобы дважды не писать `|| 0`), структуру вынесла в computed

2022-05-09 17:30 UTC, yuliyasitnikova commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +          { 'pizza__filling--third': ingredient.count === 3 },
Да, так логичнее, а по тз не очень понятно было :)

2022-05-09 17:39 UTC, yuliyasitnikova commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                  :class="`filling filling--${ingredient.value}`"
Когда делала, заметила одну вещь:

Если я передаю AppDrag пропс draggable, но при этом не регистрирую его в самом компоненте то такое использование 
`<AppDrag :draggable="false">...</AppDrag>`
"перезаписывает" значение draggable внутри компонента: 
`<div :draggable="true"/>`

Ошибок в консоли не было, но не уверена, можно ли так "переписывать" атрибуты. Объявила пропс явно и внутри компонента передаю его в значение атрибута:
`<div :draggable="draggable"/>`

2022-05-09 18:00 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                  :class="`filling filling--${ingredient.value}`"
Те атрибуты, которые мы вешаем на компонент, если не объявлены со стороны компонента как пропсы, попадают на корневой элемент компонента. Это можно отключить с помощью опции https://v2.vuejs.org/v2/api/#inheritAttrs.
Но лучше, конечно, не надеяться на это поведение, а явно объявлять пропсы, да

2022-05-09 18:10 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.currentValue = this.value;
В таких ситуациях можно при "некорректном" вводе отменить событие (через preventDefault), например

2022-05-09 18:11 UTC, merged