Подключение Vuex
htmlacademy-vue/175289-pizza-1 pull request #4
Opened 2023-09-11 05:11 UTC by yuliyasitnikova

2023-09-12 00:09 UTC, S-le requested changes
Молодец! Ты проделала большую работу и проделала её хорошо. 

Осталось доработать пару моментов:
1. п 3.3.1 из ТЗ. Не реализован функционал кнопки "Изменить" в корзине.
2. п 3.3.4 из ТЗ. Давай сделаем в данный момент функционал как у  неавторизованного пользователя. При клике в попапе на кнопку «Отлично, я жду!» производится переход на главную страницу, закрытие приводит к тому же действию.

Это небольшие правки, которые ты быстро внесешь. Жду исправления.

2023-09-12 00:09 UTC, S-le commented on src/frontend/src/modules/cart/components/CartAdditional.vue
> +            alt="Coca-Cola 0,5 литра"
Свойство _alt_ стоит тоже указывать динамически.

2023-09-12 00:09 UTC, S-le commented on src/frontend/src/modules/cart/components/CartList.vue
> +        <button type="button" class="cart-list__edit">Изменить</button>
Добавить функционал для кнопки.

2023-09-12 00:09 UTC, S-le commented on src/frontend/src/modules/cart/components/CartList.vue
> +        <b>{{ formatPrice(pizza.price) }} ₽</b>
В таком случае рекомендуется использовать вычисляемое свойство (_computed_). Вычисляемое свойство запоминает результат вычисления, а функция будет вызываться каждый раз после изменений. Ошибки в этом нет. На производительность в учебном проекте это тоже не повлияет. Но на крупном проекте такая оптимизация может пригодиться.

2023-09-12 00:09 UTC, S-le commented on src/frontend/src/modules/cart/components/CartList.vue
> +          alt="Капричоза"
Следует свойству _alt_ присваивать значение динамически.

2023-09-12 00:09 UTC, S-le reviewed
Молодец! Ты проделала большую работу и проделала её хорошо. 

Осталось доработать пару моментов:
1. п 3.3.1 из ТЗ. Не реализован функционал кнопки "Изменить" в корзине.
2. п 3.3.4 из ТЗ. Давай сделаем в данный момент функционал как у  неавторизованного пользователя. При клике в попапе на кнопку «Отлично, я жду!» производится переход на главную страницу, закрытие приводит к тому же действию.

Это небольшие правки, которые ты быстро внесешь. Жду исправления.

2023-09-25 16:25 UTC, yuliyasitnikova commented on src/frontend/src/modules/cart/components/CartList.vue
> +        <b>{{ formatPrice(pizza.price) }} ₽</b>
Не уверена, правильно ли я поняла, что требуется. Так как вычисляемое свойство не принимает аргументов, вынесла элемент списка в отдельный компонент

2023-09-25 23:16 UTC, S-le requested changes
Супер! Теперь все соответствует ТЗ.  Приступай к новой теме.

2023-09-25 23:16 UTC, S-le requested changes
Супер! Теперь все соответствует ТЗ.  Приступай к новой теме.

2023-09-25 23:16 UTC, merged